### ISSUE TITLE
Use actual tf plugin sdk version from bridge in provider upgrades

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/upgrade-provider#245] opened 2024-02-01 11:39 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

We currently upgrade providers to the newest plugin sdk version, which could be newer than the replace in the bridge we are upgrading to.

We could instead parse the bridge replace directive and use the same version in the provider.

**Comment by iwahbe** [comment] 2024-02-01 15:38
@VenelinMartinov This looks like a duplicate of https://github.com/pulumi/upgrade-provider/issues/243.

**Closed by iwahbe** 2024-02-01 15:38 UTC
Labels: kind/enhancement, resolution/duplicate
