### ISSUE TITLE
Upgrade of pulumi-azure didn't run `make upstream`

### ISSUE THREAD

**Issue by thomas11** [pulumi/upgrade-provider#163] opened 2023-09-26 19:03 UTC
```
/Users/tkappler/go/bin/upgrade-provider pulumi/pulumi-azure --kind=all
---- Setting Up Environment ----
- ✓ GOWORK="off": done
- ✓ PULUMI_MISSING_DOCS_ERROR="true": done
- ✓ PULUMI_CONVERT_EXAMPLES_CACHE_DIR="": done
---- Discovering Repository ----
- Ensure 'github.com/pulumi/pulumi-azure'
  - ✓ Expected Location: /Users/tkappler/pulumi/pulumi-azure
  - ✓ Downloading: skipped - already exists
  - ✓ Validating: done
- pull default branch
  - ✓ /usr/bin/git ls-remote --heads origin: done
  - ✓ finding default branch: master
  - ✓ /usr/bin/git fetch: done
  - ✓ /usr/bin/git checkout master: done
  - ✓ /usr/bin/git pull origin: done
- ✓ Repo kind: patched
- ✓ Planning Provider Update: 3.72.0 -> 3.74.0
- ✓ Planning Bridge Update: v3.59.0 -> v3.60.1
- ✓ Planning Plugin SDK Update: v2.27.0 -> 2.29.0
- ✓ Planning Plugin Framework Update: Unused
---- Update Artifacts ----
- Ensure Branch
  - ✓ /usr/bin/git branch: done
  - ✓ Already exists: yes
  - ✓ /usr/bin/git checkout upgrade-terraform-provider-azurerm-to-v3.74.0: done
- Update Plugin SDK
  - ✓ Update TF Plugin SDK Fork: updated
  - X /opt/homebrew/bin/go mod tidy: exit status 1:
go: finding module for package github.com/hashicorp/terraform-provider-azurerm/shim
go: github.com/pulumi/pulumi-azure/provider/v5 imports
	github.com/hashicorp/terraform-provider-azurerm/shim: module github.com/hashicorp/terraform-provider-azurerm@latest found (v1.44.0, replaced by ../upstream), but does not contain package github.com/hashicorp/terraform-provider-azurerm/shim
```

Running `make upstream` followed by the same `upgrade-provider pulumi/pulumi-azure --kind=all` worked.

**Comment by iwahbe** [comment] 2023-11-02 22:36
I believe that this is a duplicate of https://github.com/pulumi/upgrade-provider/issues/172. It was fixed in https://github.com/pulumi/upgrade-provider/pull/195. If the issue re-occurs, please raise a new issue.

**Closed by iwahbe** 2023-11-02 22:36 UTC
Labels: kind/enhancement, resolution/fixed
